language: ruby
cache: bundler
sudo: false
script: bundle exec rspec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
branches:
  only:
    - stable
    - develop
